baseurl = "https://blog.frenchtoastman.com"
title = "Toasting so much toast"
theme = "hyde"
languageCode = "en-us"
copyright = "Tyler French"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = false

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Tyler French"
    profile = "https://blog.frenchtoastman.com/posts/about"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = ""
    description = "Toasting the toast"
    github = "https://github.com/frenchtoasters"
    email = "tylerfrench2@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = "js/highlight.pack.js"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
