baseurl = "http://blog.frenchtoastman.com/"
languageCode = "en-us"
title = "Blog of thangs"
theme="hugo-darkdoc-theme"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  author = "Tyler French"


[[menu.main]]
  name="Content"
  url= "posts/"
  weight=0  
