baseurl = "http://blog.frenchtoastman.com/"
languageCode = "en-us"
title = "Blog of thangs"
theme="hugo-darkdoc-theme"

[permalinks]
  post = "/:year/:month/:title/"

[params]
    # General information
    author = "Tyler French"
    description = "This blog of things"
    copyright = "MITish"

  #demo website
  demo_site = "http://frenchtoastman.com"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/mynamemyproject"
    repo_id = "myproject"

    version = "1.0.0"
    favicon = ""

    permalink = "#"

[social]
    github  = "frenchtoasters"

[[menu.main]]
    name   = "Demo"
    url    = "demo/"
    weight = 0
